export const projectsData = [
  {
    id: 1,
    imgSrc: "/images/ggstore.png",
    title: "loja de jogos online",
    tech1: "React js",
    tech2: "NodeJs",
    tech3: "Express",
    tech4: "Sequelize",
    path: "/ggstore",
  },
  {
    id: 2,
    imgSrc: "/images/simplenote.png",
    title: "app de anotações",
    tech1: "React Native",
    tech2: "NodeJs",
    tech3: "Express",
    tech4: "sqlite3",
    path: "/notesapp",
  },
  {
    id: 3,
    imgSrc: "/images/rainsoundapp.png",
    title: "app sons de chuva",
    tech1: "React Native",
    tech2: "local storage",
    tech3: "mp3 files",
    tech4: "local time",
    path: "/rainsoundapp",
  },
  {
    id: 4,
    imgSrc: "/images/typingtext.png",
    title: "web app speed typing",
    tech1: "React js",
    tech2: "typescript",
    tech3: "cart js",
    tech4: "promodoro timer",
    path: "/speedtyping",
  },
];
